avoid-breaking-exported-api = false
cognitive-complexity-threshold = 30

disallowed-methods = [
  "std::collections::HashMap::new",
  "std::collections::HashSet::new",
  "std::time::Instant::now",
  "std::vec::Vec::swap_remove",
]

disallowed-types = [
  "std::collections::HashMap",
  "std::collections::HashSet",
]
