[package]
name = "maestria-launcher"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[features]
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-single-instance = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["sync", "time", "macros"] }
toml.workspace = true
thiserror.workspace = true
raw-window-handle = "0.6"

[target.'cfg(target_os = "linux")'.dependencies]
tauri-plugin-global-shortcut = "2"
futures-util = "0.3"
base64.workspace = true
gtk = "0.18"
gdk = "0.18"
gio = "0.18"
glib = "0.18"
gdk-pixbuf = "0.18"
ashpd = { version = "=0.12.3", default-features = false, features = ["tokio", "raw_handle", "wayland"] }
