[package]
name = "maestria-blob-fs"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
maestria-domain = { workspace = true }
maestria-ports = { workspace = true }
sha2 = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
maestria-ports = { workspace = true, features = ["contract-tests"] }
tempfile = { workspace = true }
