"""Panic and lint rule family."""

from __future__ import annotations

from . import shared
from .shared import (
    SCAN_EXTS,
    _FALLIBLE_CONSTRUCTOR_PATTERN,
    _PUBLIC_ASYNC_FN_PATTERN,
    _SERDE_TRY_FROM_PATTERN,
    _TRY_FROM_IMPL_PATTERN,
    _iter_scannable,
    _kernel_rust_files,
    _matching_delimiter,
    _named_struct_fields_with_visibility,
    _production_rust_files,
    _rust_syntax,
    _scrubbed_production,
    production_rust,
    read_text,
)
from .dependency_graph import (
    APP_CRATE_DIRS,
)
import re

FORBIDDEN_MARKERS = [r"\bTODO\b", r"\bFIXME\b"]


FORBIDDEN_RUST_LINT_BYPASSES = [
    r"#\s*!?\s*\[\s*allow\b",
    r"#\s*!?\s*\[\s*cfg_attr\s*\([^]]*\ballow\b",
    r"#\s*!?\s*\[\s*expect\b",
    r"#\s*!?\s*\[\s*cfg_attr\s*\([^]]*\bexpect\b",
]


FORBIDDEN_RUST_METHODS = [
    (
        r"\.(?:unwrap|expect|unwrap_err|expect_err|unwrap_or|unwrap_or_else|unwrap_or_default)\s*\(",
        "a forbidden Option/Result failure method",
    ),
    (r"\b(?:HashMap|HashSet)::new\s*\(", "a forbidden hash collection constructor"),
    (r"\bstd::time::Instant::now\s*\(", "a forbidden wall-clock instant"),
    (r"\.swap_remove\s*\(", "a forbidden swap_remove call"),
    # Rule 11: panics must not be intercepted either; catch_unwind turns a
    # panic into a swallowed control-flow value.
    (
        r"\b(?:std::panic::)?catch_unwind\s*\(",
        "a forbidden panic interception (catch_unwind)",
    ),
]


FORBIDDEN_UNBOUNDED_CHANNEL_PATTERNS = (
    r"\b(?:tokio::sync::)?mpsc::unbounded_channel\s*\(",
    r"\b(?:tokio::sync::)?mpsc::Unbounded(?:Sender|Receiver)\b",
    r"\bstd::sync::mpsc::channel(?:\s*::\s*<[^>]+>)?\s*\(",
    r"\bcrossbeam(?:_channel|::channel)::unbounded(?:\s*::\s*<[^>]+>)?\s*\(",
    r"\b(?:async_channel|async_std::channel)::unbounded(?:\s*::\s*<[^>]+>)?\s*\(",
    r"\bflume::unbounded(?:\s*::\s*<[^>]+>)?\s*\(",
)


GENERATED_BLOB_MARKERS = (
    "@generated",
    "DO NOT EDIT",
    "Code generated by",
    "THIS FILE IS GENERATED",
)


FORBIDDEN_STRING_ERROR_PATTERN = re.compile(
    r"^\s*type\s+Error\s*=\s*String\s*;", re.MULTILINE
)


# Whole-bug-class bans for memory unsafety and leaks. These markers have no
# legitimate use in this repository's Rust (checked against the workspace);
# `transmute` silently reinterprets bits, `static mut` is a data-race class,
# and `Box::leak`/`mem::forget` are deliberate leak hooks.
# Whole-bug-class bans for unchecked/UB-adjacent APIs. These "skip the
# check" calls (unsound UTF-8 casts, raw-pointer construction, unchecked
# indexing, `transmute_copy`, zeroed/uninitialized memory) have no
# legitimate use in this repository (census-validated against the
# workspace); the harness's confined unsafe file-handle code uses checked
# alternatives.
UNCHECKED_API_PATTERNS = (
    (r"\b(?:String::)?from_utf8_unchecked\s*\(", "a from_utf8_unchecked call"),
    (r"\bfrom_utf16_unchecked\s*\(", "a from_utf16_unchecked call"),
    (r"\b(?:std::)?slice::from_raw_parts(?:_mut)?\s*\(", "a slice::from_raw_parts call"),
    (r"\bNonNull::new_unchecked\s*\(", "a NonNull::new_unchecked call"),
    (r"\b(?:std::hint::)?unreachable_unchecked\s*\(", "an unreachable_unchecked call"),
    (r"\bget_unchecked(?:_mut)?\s*\(", "a get_unchecked call"),
    (r"\b(?:std::mem::)?transmute_copy(?:\s*::)?(?:\s*<[^>]*>)?\s*\(", "a transmute_copy call"),
    (r"\b(?:std::)?mem::zeroed\s*\(", "a mem::zeroed call"),
    (r"\b(?:std::)?mem::uninitialized\s*\(", "a mem::uninitialized call"),
)


# Task markers and unreachable guarantees as source tokens. The clippy
# `panic` gate already rejects these in every target; this scan keeps the
# ban enforced even when clippy flags are relaxed (defense-in-depth, like
# the assert-family scan). String and comment contexts are scrubbed so
# tests that reference the tokens do not self-flag.
FAILURE_TOKEN_PATTERNS = (
    (r"\btodo!\s*\(", "a todo! marker"),
    (r"\bunimplemented!\s*\(", "an unimplemented! marker"),
    (r"\bunreachable!\s*\(", "an unreachable! marker"),
)


# Host-process termination. Library crates must return typed errors;
# `process::exit` belongs only to app crates that own the process lifecycle
# (the same boundary as the console-output ban).
PROCESS_EXIT_PATTERN = re.compile(r"\b(?:std::)?process::exit\s*\(")


MEMORY_UNSAFETY_PATTERNS = (
    (
        r"\b(?:std::mem::)?transmute(?:\s*::)?(?:\s*<[^>]*>)?\s*\(",
        "a transmute call",
    ),
    (r"\bstatic\s+mut\b", "a `static mut` declaration"),
    (r"\bBox::leak\s*\(", "a Box::leak call"),
    (r"\b(?:std::)?mem::forget\s*\(", "a mem::forget call"),
)


# Process-global environment mutation. `set_var`/`remove_var`/`set_current_dir`
# mutate state every thread and future child observes, race with concurrent
# readers, and cannot be scoped; the correct mechanism is per-process
# `Command::env` or an explicit environment parameter. No repository code
# needs them (census-validated); the ban covers tests too.
ENV_MUTATION_PATTERNS = (
    (r"\b(?:std::)?env::set_var\s*\(", "a process-global env::set_var"),
    (r"\b(?:std::)?env::remove_var\s*\(", "a process-global env::remove_var"),
    (r"\b(?:std::)?env::set_current_dir\s*\(", "a process-global env::set_current_dir"),
)


# Debugging leftovers and unconditional stdout/stderr writes. Library crates
# must log through `tracing`; app binaries own their console output.
DEBUG_OUTPUT_PATTERNS = (
    (r"\bdbg!\s*\(", "a dbg! debug-print call"),
    (r"\bprint!\s*\(", "a print! stdout call"),
    (r"\bprintln!\s*\(", "a println! stdout call"),
    (r"\beprint!\s*\(", "an eprint! stderr call"),
    (r"\beprintln!\s*\(", "an eprintln! stderr call"),
)


# Rule 1/21: kernel code has no hidden global state or uncontrolled
# concurrency. Shared ownership and interior mutability are the two Rust
# mechanisms that introduce both; the in-memory port adapters under
# maestria-ports are test doubles exempted by their adapter role.
KERNEL_INTERIOR_MUTABILITY_PATTERNS = (
    r"\bRc\s*<",
    r"\bRefCell\s*<",
    r"\bCell\s*<",
    r"\bMutex\s*<",
    r"\bRwLock\s*<",
    r"\bOnceLock\b",
    r"\bOnceCell\b",
    r"\bLazyLock\b",
    r"\bthread_local!",
)


# Rule 11 defense-in-depth: `assert!`/`assert_eq!`/`assert_ne!`/`assert_matches!`
# panic on failure like `panic!` does, so production code must use typed
# errors. (clippy::panic already gates this; the checker keeps it enforced
# even when clippy flags are relaxed.) `debug_assert!` is a release no-op and
# stays allowed.
_PRODUCTION_ASSERT_PATTERN = re.compile(
    r"\bassert(?:!|_eq!|_ne!|_matches!)\s*\("
)


def scan_markers() -> list[str]:
    violations = []
    for candidate in _iter_scannable(shared.ROOT):
        if shared._is_checker_source(candidate):
            continue
        if candidate.suffix.lower() not in SCAN_EXTS:
            continue
        content = read_text(candidate)
        if content is None:
            continue
        if any(re.search(pattern, content) for pattern in FORBIDDEN_MARKERS):
            violations.append(str(candidate.relative_to(shared.ROOT)))
    return violations


def scan_rust_lint_bypasses() -> list[str]:
    violations = []
    for source in _production_rust_files(skip_tests=False):
        content = read_text(source)
        if content is None:
            continue
        if any(re.search(pattern, content) for pattern in FORBIDDEN_RUST_LINT_BYPASSES):
            violations.append(str(source.relative_to(shared.ROOT)))
    return violations


def scan_unbounded_channels() -> list[str]:
    violations = []
    for source in _production_rust_files(skip_tests=False):
        content = read_text(source)
        if content is None:
            continue
        if any(
            re.search(pattern, content)
            for pattern in FORBIDDEN_UNBOUNDED_CHANNEL_PATTERNS
        ):
            violations.append(
                f"{source.relative_to(shared.ROOT)} contains an unbounded internal channel"
            )
    return violations


def scan_rust_forbidden_methods() -> list[str]:
    violations = []
    for source in _production_rust_files(skip_tests=False, sorted_=True):
        content = read_text(source)
        if content is None:
            continue
        for pattern, description in FORBIDDEN_RUST_METHODS:
            if re.search(pattern, content):
                violations.append(f"{source.relative_to(shared.ROOT)} contains {description}")
    return violations


def scan_generated_blobs() -> list[str]:
    """Rule 38: no generated blobs under production source paths.

    A production Rust file carrying a code-generation marker is either
    vendored output (which must move out of the tree) or hand-edited
    generated code (which must become a real source file). Test fixtures
    are exempt: generated test data is legitimate.
    """
    violations = []
    for source in _production_rust_files(skip_tests=True):
        content = read_text(source)
        if content is None:
            continue
        production = production_rust(content)
        for marker in GENERATED_BLOB_MARKERS:
            if marker in production:
                violations.append(
                    f"{source.relative_to(shared.ROOT)} contains generated-code marker {marker!r}"
                )
                break
    return violations


def scan_string_typed_errors() -> list[str]:
    """Rule 24: failure information is preserved; a `TryFrom`/`FromStr`
    implementation whose error type is a bare `String` discards the typed
    validation variants at the conversion boundary."""
    violations = []
    for source in _production_rust_files(skip_tests=True):
        content = read_text(source)
        if content is None:
            continue
        production = production_rust(content)
        for match in FORBIDDEN_STRING_ERROR_PATTERN.finditer(production):
            line_number = content.count("\n", 0, match.start()) + 1
            violations.append(
            f"{source.relative_to(shared.ROOT)}:{line_number} uses String as a "
            "conversion error type; use a typed error"
        )
    return violations


def scan_memory_unsafety_markers() -> list[str]:
    """Ban the memory-unsafety and leak marker classes outright.

    `transmute` reinterprets bits without a checked conversion, `static mut`
    is a data-race class even under single-threaded use, and
    `Box::leak`/`mem::forget` deliberately leak memory. No repository code
    needs them; the ban covers tests too because these classes are never a
    legitimate test strategy.
    """
    violations = []
    for source in _production_rust_files(skip_tests=False):
        content = read_text(source)
        if content is None:
            continue
        for pattern, description in MEMORY_UNSAFETY_PATTERNS:
            if re.search(pattern, content):
                violations.append(
                    f"{source.relative_to(shared.ROOT)} contains {description}"
                )
    return violations


def scan_unchecked_apis() -> list[str]:
    """Ban unchecked/UB-adjacent API calls outright.

    These "skip the check" calls (unsound UTF-8 casts, raw-pointer
    construction, unchecked indexing, `transmute_copy`, zeroed/uninitialized
    memory) are never a legitimate strategy in this repository (census
    validated); the harness's confined unsafe file-handle code uses checked
    alternatives. String and comment contexts are scrubbed so documentation
    references do not self-flag.
    """
    violations = []
    for source in _production_rust_files(skip_tests=False):
        content = read_text(source)
        if content is None:
            continue
        scrubbed = _rust_syntax(content)
        for pattern, description in UNCHECKED_API_PATTERNS:
            if re.search(pattern, scrubbed):
                violations.append(
                    f"{source.relative_to(shared.ROOT)} contains {description}"
                )
    return violations


def scan_failure_tokens() -> list[str]:
    """Ban `todo!`/`unimplemented!`/`unreachable!` repo-wide.

    Defense-in-depth alongside the clippy `panic` gate: these markers are
    never shipped code or test strategy. String and comment contexts are
    scrubbed so tests that reference the tokens do not self-flag.
    """
    violations = []
    for source in _production_rust_files(skip_tests=False):
        content = read_text(source)
        if content is None:
            continue
        scrubbed = _rust_syntax(content)
        for pattern, description in FAILURE_TOKEN_PATTERNS:
            if re.search(pattern, scrubbed):
                violations.append(
                    f"{source.relative_to(shared.ROOT)} contains {description}"
                )
    return violations


def scan_process_exit() -> list[str]:
    """Ban host-process termination outside app crates.

    Library crates must return typed errors; `process::exit` belongs only to
    app crates that own the process lifecycle (the same boundary as the
    console-output ban).
    """
    violations = []
    for source in _production_rust_files(skip_tests=False):
        content = read_text(source)
        if content is None:
            continue
        is_app = any(segment in APP_CRATE_DIRS for segment in source.parts)
        if is_app:
            continue
        if PROCESS_EXIT_PATTERN.search(content):
            violations.append(
                f"{source.relative_to(shared.ROOT)} contains a process::exit call outside an app crate"
            )
    return violations


def scan_env_mutation() -> list[str]:
    """Ban process-global environment mutation outright.

    `set_var`/`remove_var`/`set_current_dir` mutate state every thread and
    future child observes; they race with concurrent readers and cannot be
    scoped to a single test or command. Per-process configuration belongs in
    `Command::env` or an explicit environment parameter. The ban covers
    tests too because the mutation class is never a legitimate strategy.
    """
    violations = []
    for source in _production_rust_files(skip_tests=False):
        content = read_text(source)
        if content is None:
            continue
        for pattern, description in ENV_MUTATION_PATTERNS:
            if re.search(pattern, content):
                violations.append(
                    f"{source.relative_to(shared.ROOT)} contains {description}"
                )
    return violations


def scan_debug_output() -> list[str]:
    """Ban debugging leftovers and library console writes.

    `dbg!` is a debugging leftover anywhere, including tests. The
    `print!`/`println!`/`eprint!`/`eprintln!` family is only legitimate in
    app crates that own a console; library crates must emit through
    `tracing` so output is structured, filtered, and testable.
    """
    violations = []
    for source in _production_rust_files(skip_tests=False):
        content = read_text(source)
        if content is None:
            continue
        is_app = any(segment in APP_CRATE_DIRS for segment in source.parts)
        for pattern, description in DEBUG_OUTPUT_PATTERNS:
            if description.startswith("a dbg!"):
                continue  # dbg! is banned everywhere; handled below.
            if is_app:
                continue  # App crates own their console output.
            if re.search(pattern, content):
                violations.append(
                    f"{source.relative_to(shared.ROOT)} contains {description}"
                )
        if re.search(r"\bdbg!\s*\(", content):
            violations.append(
                f"{source.relative_to(shared.ROOT)} contains a dbg! debug-print call"
            )
    return violations


def scan_kernel_interior_mutability() -> list[str]:
    """Rule 1/21: kernel domain and governance code has no shared ownership
    or interior mutability.

    `Rc`/`RefCell`/`Cell`/`Mutex`/`RwLock`/`OnceLock`/`OnceCell`/`LazyLock`
    and `thread_local!` introduce hidden global state or uncontrolled
    concurrency into deterministic code. The in-memory port adapters under
    `maestria-ports/src/in_memory` are test doubles with an adapter role and
    are exempt; domain and governance are not.
    """
    violations = []
    for kernel_root in shared.KERNEL_ROOTS:
        for source in (kernel_root / "src").rglob("*.rs"):
            if kernel_root.name == "maestria-ports" and "in_memory" in source.parts:
                continue
            content = read_text(source)
            if content is None:
                continue
            rel = source.relative_to(shared.ROOT)
            for pattern in KERNEL_INTERIOR_MUTABILITY_PATTERNS:
                if re.search(pattern, content):
                    violations.append(
                        f"{rel} contains interior-mutability or shared-ownership "
                        f"token {pattern!r}"
                    )
    return violations


def scan_production_asserts() -> list[str]:
    """Rule 11 defense-in-depth: shipped code must not assert.

    `assert!`/`assert_eq!`/`assert_ne!`/`assert_matches!` panic on failure
    exactly like `panic!`, so production code must return typed errors.
    clippy::panic already gates this in CI; the checker keeps the class
    banned even when clippy flags are relaxed. Test sources and inline
    `#[cfg(test)]` items are exempt.
    """
    violations = []
    for source in _production_rust_files(skip_tests=True):
        content = read_text(source)
        if content is None:
            continue
        production = _scrubbed_production(source)
        for match in _PRODUCTION_ASSERT_PATTERN.finditer(production):
            line_number = content.count("\n", 0, match.start()) + 1
            violations.append(
                f"{source.relative_to(shared.ROOT)}:{line_number} contains a production "
                "assert; use a typed error"
            )
    return violations


def _doc_block_above(text: str, position: int) -> str:
    """Contiguous doc-comment (`///`) lines immediately above *position*,
    skipping blank lines and single-line attributes."""
    lines = text[:position].splitlines()
    docs: list[str] = []
    for line in reversed(lines):
        stripped = line.strip()
        if stripped.startswith("///"):
            docs.append(stripped)
        elif not stripped or stripped.startswith("#[") or stripped.startswith("//!"):
            continue
        else:
            break
    return "\n".join(reversed(docs))


def scan_cancellation_docs() -> list[str]:
    """Rule 34: public async operations document cancellation behavior.

    A `pub async fn` without a doc comment mentioning cancellation leaves
    callers unable to reason about drop/stale-result semantics.
    """
    violations = []
    for source in _production_rust_files(skip_tests=True):
        content = read_text(source)
        if content is None:
            continue
        production = production_rust(content)
        for match in _PUBLIC_ASYNC_FN_PATTERN.finditer(production):
            docs = _doc_block_above(production, match.start())
            if not re.search(r"\bcancel", docs, re.IGNORECASE):
                violations.append(
                    f"{source.relative_to(shared.ROOT)} `{match.group(1)}` is a public async "
                    "operation without a # Cancellation doc section"
                )
    return violations


def scan_bypassable_validation() -> list[str]:
    """Rule 56: validated kernel values must not expose bypassable constructors.

    A kernel struct that (a) carries a validating serde `try_from` conversion
    or a fallible constructor, and (b) still exposes public fields, lets
    callers build values that skip the validation. The validated model is
    private fields plus a fallible boundary constructor (the SearchPlan /
    ContentHash pattern).
    """
    violations = []
    for source in _kernel_rust_files(skip_tests=True):
        content = read_text(source)
        if content is None:
            continue
        production = _scrubbed_production(source)
        if not production:
            continue
        rel = source.relative_to(shared.ROOT)

        for struct_name, fields in _named_struct_fields_with_visibility(production):
            public_fields = [name for name, _, is_pub in fields if is_pub]
            if not public_fields:
                continue
            validated = False
            # (a) a serde try_from attribute whose next item is this struct
            for attr in _SERDE_TRY_FROM_PATTERN.finditer(production):
                between = production[attr.end() :]
                next_item = re.search(
                    r"^\s*(?:pub(?:\s*\([^)]*\))?\s+)?"
                    r"(?:struct|enum|impl|fn|mod|type|const)\s+",
                    between,
                    re.MULTILINE,
                )
                if (
                    next_item is not None
                    and between[next_item.start() :].lstrip().startswith(
                        f"struct {struct_name}"
                    )
                ):
                    validated = True
                    break
            if not validated:
                # (b) a fallible constructor inside `impl <struct_name>`
                for candidate in _FALLIBLE_CONSTRUCTOR_PATTERN.finditer(production):
                    if _function_belongs_to_struct(
                        production, candidate.start(), struct_name
                    ):
                        validated = True
                        break
            if not validated:
                # (c) a `TryFrom<...> for <struct_name>` conversion
                for impl_match in _TRY_FROM_IMPL_PATTERN.finditer(production):
                    if impl_match.group(1) == struct_name:
                        validated = True
                        break
            if validated:
                violations.append(
                    f"{rel} struct `{struct_name}` exposes public fields "
                    f"({', '.join(public_fields)}) alongside a validating "
                    "conversion; make fields private and construct through a "
                    "fallible boundary constructor"
                )
    return violations


def _function_belongs_to_struct(text: str, fn_start: int, struct_name: str) -> bool:
    """True when the fallible constructor at *fn_start* sits inside an
    `impl <struct_name> { ... }` block."""
    impl_matches = list(re.finditer(r"impl\s+(?:<[^>]*>\s+)?(\w+)\s*\{", text))
    for impl_match in reversed(impl_matches):
        opening = text.find("{", impl_match.start())
        closing = _matching_delimiter(text, opening, "{", "}")
        if closing is None:
            continue
        if opening < fn_start < closing:
            return impl_match.group(1) == struct_name
    return False
