[package]
name = "maestria-parsers"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
lopdf = { workspace = true }
maestria-domain = { workspace = true }
maestria-ports = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
maestria-ports = { workspace = true, features = ["contract-tests"] }
